### ISSUE TITLE
Add cursor CSS that indicates that a control is droppable

### ISSUE THREAD

**Issue by BrennanMcDonald** [bevacqua/dragula#115]
Adding the code 
```javascript
initialContainers.forEach(function(e,i,d){
  		var children = [].slice.call(e.children);
  		children.forEach(function(e1,i1,d1){
  			e1.className += " dragula-draggable";
  			e1.className = e1.className.trim();
  		});
  })
```
and the style
```css
.dragula-draggable {
	  cursor: move;
	  cursor: grab;
	  cursor: -moz-grab;
	  cursor: -webkit-grab;
}
```
would apply a hand/move cursor to every draggable element that the user has provided.
This would make it much easier for an end user to determine which elements are draggable.

**Comment by bevacqua** [comment]
This is what we do for the demo, but not part of the core experience, as it's not desirable in every use case.

```css
.container div,
.gu-mirror {
  margin: 10px;
  padding: 10px;
  background-color: rgba(0, 0, 0, 0.2);
  transition: opacity 0.4s ease-in-out;
  cursor: move;
  cursor: grab;
  cursor: -moz-grab;
  cursor: -webkit-grab;
}
.gu-unselectable {
  cursor: grabbing;
  cursor: -moz-grabbing;
  cursor: -webkit-grabbing;
}
```

https://github.com/bevacqua/dragula/blob/master/example/example.css#L134-L143
