### ISSUE TITLE
`accepts` is never called on iOS 8.4.1

### ISSUE THREAD

**Issue by Bushjumper** [bevacqua/dragula#164]
We're using Dragula JS in a hybrid mobile app. We noticed that after upgrading to the latest iOS version earlier (8.4.1), dragging doesn't work as it previously did.

Dragging an item starts ok but the 'accepts' callback is never triggered because getElementBehindPoint() seems to always return the whole document, not the specific element behind the point. This means that dropping isn't possible.

Of course, this is probably more of an iOS issue than a Dragula one, but I thought it worth mentioning here in case others have the same problem, or there may be a workaround or known fix?

**Comment by bevacqua** [comment]
I have a few action items for you, if you don't mind.

- Could this be related? http://stackoverflow.com/questions/19007553/document-elementfrompointx-y-pure-javascript-alternative

- Could you log the values of `x` and `y`? Maybe those are the crux of the problem, and we're getting clientX/clientY wrong for iOS 8.4.1

- Otherwise we probably should look into adding a case where if the document body is returned we make one more attempt at getting the element, but manually, looping over the DOM somehow.

**Comment by bevacqua** [comment]
I couldn't reproduce this issue on the demo page.

**Comment by fluff** [comment]
Having a similar issue in an in-house app (we are using Bootstrap3 and jQuery 1.11). 

We are using a "moves:" function to restrict drag-starts to a particular class of drag-handles, but we don't have any custom "accepts:" function. Dragging starts fine, but dragula doesn't seem to find any valid drop points, so .on('drop') never triggers and whatever is being dragged just pops back to its original position.

The iOS simulator (which is on version "8.4.0", there are no 8.4.1 updates for the simulator) works on both the demo page and in our app.

A real iPhone6+ running iOS 8.4.1 works on the demo page, but not in our app.

**Comment by fluff** [comment]
For us, the root cause seemed to be the following bootstrap style:
```css
.col-xs-1, .col-sm-1, .col-md-1, .col-lg-1, .col-xs-2, .col-sm-2, .col-md-2, .col-lg-2, .col-xs-3, .col-sm-3, .col-md-3, .col-lg-3, .col-xs-4, .col-sm-4, .col-md-4, .col-lg-4, .col-xs-5, .col-sm-5, .col-md-5, .col-lg-5, .col-xs-6, .col-sm-6, .col-md-6, .col-lg-6, .col-xs-7, .col-sm-7, .col-md-7, .col-lg-7, .col-xs-8, .col-sm-8, .col-md-8, .col-lg-8, .col-xs-9, .col-sm-9, .col-md-9, .col-lg-9, .col-xs-10, .col-sm-10, .col-md-10, .col-lg-10, .col-xs-11, .col-sm-11, .col-md-11, .col-lg-11, .col-xs-12, .col-sm-12, .col-md-12, .col-lg-12 {
  position: relative;
}
```
Our workaround was to add: ```style="position:static"``` to the containing ```<div class="col-md-6">```
