### ISSUE TITLE
when drag element ,the element height has changed then the offsetY is a wrong num.

### ISSUE THREAD

**Issue by aibotian** [bevacqua/dragula#583]
when drag element ,the element height has changed then the offsetY is a wrong num.

**Comment by aibotian** [comment]
@bevacqua

**Comment by MostafaEbrahimi** [comment]
Please provide more information.
Before that consider these information about Dragula working method.
When element is in dragging mode Dragula creates new node ( clone child ) and set `gu-mirror` class to it and working with created element by changing mouseevent.
this is `gu-mirror` class.
```css
.gu-mirror {
  position: fixed !important;
  margin: 0 !important;
  z-index: 9999 !important;
  opacity: 0.8;
  -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=80)";
  filter: alpha(opacity=80);
}
```
and this is a sample created element
```html 
<div class="gu-mirror" style="width: 700px; height: 22px; left: 478.5px; top: 307.734px;">Drags don't trigger click events.</div>
```
